### ISSUE TITLE
Online demos of the components?

### ISSUE THREAD

**Issue by cxw42** [vanillawc/vanillawc#14]
# Online demos of the components

Since Chrome won't load scripts from `file://` pages, you can't demo these components on a local machine without a local server (I use `devd`).  I think it would be nice to have online demos of the components to reduce the number of steps required to see results.  If we set up a standard demo platform, we could reduce the effort required to create demos when new components are added to the repository.

The existing components have `/demo/index.html` files that use `../src/foo.js`.  One way to keep that structure would be to create `vanillawc.github.io` with two branches: `master` (deployment) and `staging`.  The `staging` branch would include all of the repos in the vanillawc organization as submodules.  We could run a build job that would `git submodule update --init --recursive` in a `staging` worktree and then copy the results to a `master` worktree for deployment.  The build job could also update `/index.html` to list all of the available demos, if we were that sophisticated :) .

This is certainly not the only option, but it has the advantage that it doesn't require any changes to the existing repos, and it doesn't cost anything ;) .  What do you think?

**Comment by evanplaice** [comment]
Good point. Usability and lowering barriers for users really needs to be improved.

Instructions on how to run the demos locally need to be added to the README docs.

If you run `npm start` the component will load in live-server.

For individual demos, we could reuse the jquery-csv demo template. It has 2 sections, a syntax highlighted code block, and what the code block outputs. It's very minimalistic and 'view source' friendly for users.

http://typeiii.github.io/jquery-csv/examples/to-array.html

I like the idea of a centralized collection of demos. Not sure about git submodules tho, I don't have much experience using them.

One thing to consider. The main `vanillawc` repo will be included in some of the web component repos as a dev dep. I use it for shared resources (ex icons).

**Comment by evanplaice** [comment]
I was going to start creating demos under codepen but the problem there is they'd all be under my personal account.

That's not very useful for sharing the work with others. Ideally, I'd like to have other active contributors so I'm not the single point of failure.

**Comment by evanplaice** [comment]
How about now? https://github.com/vanillawc/wc-markdown

I added some more facilities. There are a demos that can be opened directly from the README or locally using `npm run start`.

In addition, the previous demo that I use for manual testing can be launched with `npm run dev` and from there a debugger can be attached from within VSCode to enable breakpoints/watches/etc.

**Comment by cxw42** [comment]
I'll check it out!  When I have a chance, I'll also make a mock-up of my proposal for testing and comparison.

**Comment by evanplaice** [comment]
Well, now there is `<wc-demo>` for demoing components.

If Webcomponents.dev can fit the need, the demos may be moved there in the future.

Going to close this as solved for now.
