### ISSUE TITLE
wc-json

### ISSUE THREAD

**Issue by evanplaice** [vanillawc/vanillawc#16]
## What does this WC do?

The web component consumes a JSON file and creates an interactive UI from its contents

## References

- [Demo on Webcomponents.dev](https://webcomponents.dev/edit/VXr2i1M8U1s4He9bOdII)

**Comment by evanplaice** [comment]
@georges-gomes Feel free to change this however you prefer. The only constraint for this org is that the web component starts with the `wc-` prefix.

Do you have a repo for this already that can be transferred over or do we need to scaffold one from scratch?

**Comment by georges-gomes** [comment]
Hi! I'm actually pushing to github straight from webcomponents.dev.
Let me see if I can point it here instead.
Talk to you again soon

**Comment by georges-gomes** [comment]
Webcomponents.dev was not supporting organisation where I’m a member only (as opposed to owner). We did the change and should be going live soon. After that I will be ready to push the repo automatically 👍

**Comment by evanplaice** [comment]
Awesome! I'm looking forward to seeing how it works.

I took a shot at using one of the existing WC on webcomponents.dev over the weekend. I think it would be a perfect replacement for the current approach to building component demos.

There are a few blockers:

- changing the license from ISC -> MIT didn't work
- I'd like the option (ex checkbox) to remove testing support

**Comment by georges-gomes** [comment]
Wow we would be honored 🙇‍♂️
Let me see how quick we can fix that!!

We also have an organisation support so I will create a vanillawc organisation and add you so you can have multiple people collaborating on the demos. And I will be pleased to help! 👍

**Comment by georges-gomes** [comment]
@evanplaice you should have the organisation in your avatar menu now

![image](https://user-images.githubusercontent.com/5250572/69704958-daf86d00-10f4-11ea-9852-3eaa1521949c.png)

**Comment by evanplaice** [comment]
Cool. This'll have to wait until mañana. I'm done for the night. TTYL

**Comment by georges-gomes** [comment]
(Licence ISC->MIT fixed)

**Comment by georges-gomes** [comment]
Hi @evanplaice 
Platform is updated and I was able to push to the `wc-json` repository.
Let me know if you have comments and I will adjust accordingly 👍
Cheers
