### ISSUE TITLE
addition of a chat group

### ISSUE THREAD

**Issue by therealadityashankar** [vanillawc/vanillawc#29]
## Notes
Hey @evanplaice, I'm willing to contribute more to the wc-codemirror project, however, I do have alot of questions with regard to the code, it'd be great if there could be a chat group where I could ask these questions, since these doubts are too simple to file an entire issue for

I'm most comfortable with discord, since deno, xz and webtorrent are 3 open source projects I follow the chat of, and all three of them use discord, I basically the tab pinned in my browser

thanks in advance !

**Comment by evanplaice** [comment]
Good idea :+1: Here's the link to join https://discord.gg/yGqcGAt

**Comment by evanplaice** [comment]
@therealadityashankar When you join I'll add you as a Moderator. I've never moderated a Discord so, if you have, I could use some help setting things up.

The server is called VanillaJS so it can be used for both the VanillaWC and VanillaES organizations.

It needs
- a logo (generic yellow/black JS logo will work)
- a badge/link that can be added to all of the project READMEs

**Comment by therealadityashankar** [comment]
awesome, thanks !
