### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by evanplaice** [vanillawc/vanillawc#3]
# Packaging for Production

## Description

For a basic WC that doesn't require any external deps this may be as simple as pointing the main/module fields to the source file.

For a more complex WC, what's the best strategy to produce a production-ready build?

What about assets (ex SVG/images/CSS)?

Is there existing tooling available already that makes this process easy (ex PikaPkg)?

Relying heavily on `node_modules` on the front-end is **not** the answer, we need an approach that (ideally) tree shakes out any unnecessary/unused dependencies.

## Notes (optional)

From what I can tell so far. It appears that components provided by `open-wc` are pulling dependencies from a `web_modules` folder. AFAIK, that's what PikaPkg uses. Maybe this is already a solved issue and we can save the effort by relying on their toolchain instead.

**Comment by bennypowers** [comment]
open-wc doesn't depend on pikapkg. At the moment it recommends rollup, so I'm not sure what's causing the effects you're seeing.

However, I'd love to see this project use pika/web, I think that would fit in perfectly with what you're trying to achieve here

**Comment by matthewp** [comment]
I'd rather stay agnostic to how people build their stuff.  It would be nice to bundle your own code as to not create waterfalls for users of your components, but aside from that people can do what they want. 

For assets I would just include those in the packages. You can refer to them using `import.meta.url`.

```js
const imgUrl = new URL('./logo.svg', import.meta.url).toString();
const img = document.createElement('img');
img.src = imgUrl;
```

**Comment by evanplaice** [comment]
Issues:

**The import story for browsers still sucks**

Not to throw shade at the browser implementors, they're doing a great job. The issue is, without bare imports being provided by source maps, wiring up external deps is still a pain. Until/if source maps aren't an option, the ideal solution is to package code as a single import.

**Packaging 'best practices' inertia**

The current supposed best practices are to throw everything and the kitchen sink into a build tool then serve it up with a build-tool-specific dev server. From that workflow I think we can get rid of the requirement for a dev server, as well as minification by default.

-----

With that said I can see 3 common use cases:

1. Single file self-contained WC

This is the ideal use case. Everything is served from a single file in the root dir of the package. No bundling necessary.

2. WC with external deps

The WC has some extended capabilities that require importing additional capabilities from an external package. The production-ready source is still contained in a single file in the root dir, but to make that happen requires an explicit build process.

3. WC with multiple sources

It may be valuable for some WC packages to expose multiple files for different use cases (ex ES vs legacy-es5). The prod sources should still be placed in the root dir, there's just more than one.

@bennypowers Thanks for the input. I did some more reading thru the open-wc materials and what their materials on building with rollup are awesome.

I'm still not clear on what the installation process should look like. Pika looks cool but requires users to learn a new tool and build issues become a user-facing problem. That would suck from a project support perspective. Can Pika just copy specific files over without bundling?

@matthewp For simple WC I completely agree. For WC that require deps, DX is a problem.

```javascript
import Prism from '/node_modules/prism-es6/prism.js';
```

This works for dev but when the user installs this package they'll need to have that specific dep available in `node_modules` on their prod server. IMO, prod should *never* include `node_modules` or require users to install packages in a specific manner. The idea here is to get rid of the tree of deps altogether.

**Comment by matthewp** [comment]
You could use external urls instead:

```js
import Prism from 'https://unpkg.com/prism-es6/prism.js';
```

**Comment by evanplaice** [comment]
That would work for online demos (ex codepen) and such but would break for offline use. 

Ex You're working on a site/app out and the internet connection is flaky. One cache clearing hard reload and you're screwed.

Local install has to be available as an option.

**Comment by evanplaice** [comment]
Whelp. I've been bashing my head against my screen over this for the past day. It looks like Pika/web is still too immature to use.

AFAICT, when a user runs `npx @pika/web` it installs all deps, builds the source, then takes the one file built from source and dumps it into `web_modules`. There are no folders in `web_modules` so deps that require additional assets (ex css, svg, plugins) are a no-go.

For `wc-markdown` I'm going to settle with providing a dist/ dir that includes the bundled source as well as any required assets. bundling via rollup is super easy.

**Comment by cxw42** [comment]
I'm a Brunch and RequireJS user, so am speaking up here for everyone who doesn't use webpack or rollup ;) .  I don't have any answers either, unfortunately.  Some other thoughts -

- Small assets can be rolled into the JS as `data` URLs
- [preprocessor](https://www.npmjs.com/package/preprocessor) does C-style preprocessing of JS files, and doesn't have very many dependencies (only one direct, in fact).  If we needed a lightweight build or customization step, maybe some of what we need could be accomplished with preprocessor.
- **Edit** HTML can be rolled into JS with `<template>` per [this SO answer](https://stackoverflow.com/a/35385518/2877364).  Maybe monolithic JS files could be possible, with rollup or with a bit of lightweight tooling support for a custom build step (preferably a parameterless build step, so there's no learning curve for a new tool).

**Comment by evanplaice** [comment]
PrismJS, the library used for syntax highlighting has almost a dozen different css themes and like 350 extension files to support highlighting every language under the sun. That pretty much rules out inlining.

Rollup is actually very good. Super simple config and if the deps support ESM natively there's a good chance bundling can tree-shake out any unused code.

I guess... Packaging isn't really the issue. Installation is. Installing FE code into node_modules sucks but there's pretty much no alternative.

On a positive note, since all external deps are inlined, they can be marked as `peerDependencies` so they don't get installed when users install the package. It should literally only install 1 package.

**Comment by evanplaice** [comment]
Just stumbled onto the package [frontend-dependencies][]. This looks **very** promising. Install the packages as normal, then as a `postInstall` script it'll copy the files over from `node_modules` based on the settings defined in `package.json`.

It could use a little work (ie conversion to CLI for use w/ npx) but this looks promising. 

[frontend-dependencies]: https://github.com/msurdi/frontend-dependencies

**Comment by cxw42** [comment]
Another possible source of inspiration that popped up in the GitHub "you may also like" pane - https://github.com/abraham/nutmeg .  I haven't used it myself.
