### ISSUE TITLE
Dialog boxes? (especially modal dialogs)

### ISSUE THREAD

**Issue by cxw42** [vanillawc/vanillawc#7]
# Dialog boxes, especially modal dialogs

## Description

I would be interested in a modal-dialog component.  I also think that people might find more use cases for non-modal dialogs if they were easier to use (e.g., encapsulated in a vanillawc! :) ).  

Currently I use rmodal in TabFern, but it requires a fair amount of hand-coding to coordinate the JS and CSS ([JS](https://github.com/cxw42/TabFern/blob/issue35/app/win/main_tl.js#L336); [CSS](https://github.com/cxw42/TabFern/blob/issue35/static/win/main.html#L44)).  My code would definitely benefit from more effective encapsulation.

Would others find a dialog component useful?

## References

- [rmodal](https://rmodal.js.org/) - a pure-JS+CSS modal dialog

**Comment by evanplaice** [comment]
That sounds like a great idea. If you rely on lightDOM (ie don't add a shadowDOM) then the modals can still be styled by global CSS. 

We could probably build the dialog off of http://flouthoc.github.io/uglipop.js/.

IMO, I like utlipop's drop shadow effect. rmodal's animation is a bit much but the content structure (ie title, contents, button) looks ideal. Centering both should be easy with flexbox.

@cxw42 Did you want to work on this?

**Comment by cxw42** [comment]
@evanplaice Thanks for the invitation and feedback!  I hadn't seen uglipop before.

I unfortunately do not have bandwidth at the moment (whence Discussion and not Proposal ;) ).  I'm happy to work on it when I have the chance, but if somebody with more experience beats me to it, I won't be sad :) .

**Comment by matthewp** [comment]
I use a custom dialog at the moment, but once https://caniuse.com/#feat=dialog is released in Safari there won't be a need. Just putting it out there as consideration for anyone who wants to take this on.

**Comment by evanplaice** [comment]
Good point. From the looks of it, the new dialog element allows for custom styling and can be called with `dialog.showModal()` to add a backdrop that is also style-able via the `::backdrop` CSS prop. It even includes built-in form support that submits to an `<output>` element. Pretty slick.

I don't see much point in implementing a WC if there's already a standard for it. IMO, I'd rather focus that energy on other non-standard elements.

**Comment by cxw42** [comment]
@matthewp thanks for the tip.  From a look at the [dialog-polyfill demos](https://demo.agektmr.com/dialog/), I wonder if there might be value in an element that combines the dialog+form to reduce boilerplate.

Re. Safari, caniuse links to the [bug](https://bugs.webkit.org/show_bug.cgi?id=84635) - opened in 2012, not assigned to anyone.  I'm not holding my breath :) .  Safari does support autonomous custom elements, so there might be value there.

**Comment by matthewp** [comment]
Yeah, not sure when/if Safari is going to pick it up. And I do use a custom web component dialog in my apps, not `<dialog>` for this reason, but to me the standard being there tips the balance away from it being worth the trouble making a super polished open-source one. Just me of course.
